#! /bin/tcsh -f

# This the main NetCTL 1.2 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:      2008 Feb 17     launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetCTL 1.2a directory (mandatory)
setenv  CTLHOME /home/nuzun/Tools/netCTL-1.2b

# determine where to store temporary files (must be writable to all users)
setenv  TMPDIR  /home/nuzun/scratch/netCTL-1.2b

# determine platform (do not change this unless you don't have 'uname'!)
setenv  UNIX    `uname -s`
setenv  AR      `uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETCTL $CTLHOME/$PLATFORM

# main ========================================================================
if ( -x $NETCTL/bin/netCTL ) then
   $NETCTL/bin/netCTL $*
else
   echo netCTL: no binaries found for $PLATFORM
endif

# end of script ===============================================================
