#! /bin/tcsh -f

# This the main NetMHCIIpan 3.1 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2014 Dec 20
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCIIpan 3.1 directory (mandatory)
setenv	NMHOME	/home/nuzun/Tools/netMHCIIpan-3.1

# determine where to store temporary files (must be writable to all users)

if ( ${?TMPDIR} == 0 ) then
	setenv  TMPDIR  /home/nuzun/scratch/netMHCIIpan-3.1
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv PLATFORM $NMHOME/$PLATFORM
setenv NETMHCIIpan $NMHOME

# main ========================================================================
if ( -x $NETMHCIIpan/NetMHCIIpan-3.1.pl ) then
   $NETMHCIIpan/NetMHCIIpan-3.1.pl $*
else
   echo $NETMHCIIpan/NetMHCIIpan-3.1.pl not found
endif

# end of script ===============================================================
