#! /bin/tcsh -f

# This the main NetMHCII 2.2 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2009 Nov 25th	launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCII 2.2 directory (mandatory)
setenv	NMHOME	/home/nuzun/Tools/netMHCII-2.2

# determine where to store temporary files (must be writable to all users)
setenv	TMPDIR	/home/nuzun/scratch/netMHCII-2.2

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv NETMHCII $NMHOME/$PLATFORM
#setenv NETMHCII $NMHOME


# main ========================================================================
if ( -x $NETMHCII/bin/netMHCII ) then
   $NETMHCII/bin/netMHCII $*
else
   echo netMHCII: no binaries found for $PLATFORM
endif

# end of script ===============================================================
